---
".gitignore":
  paths:
  - import
  - "!build/vendor/"
".gitlab-ci.yml":
  delete: true
".rubocop.yml":
  default_configs:
    inherit_from: ".rubocop_todo.yml"
    require:
    - rubocop-i18n
    - rubocop-rspec
    AllCops:
      Exclude:
      - lib/puppet/type/*
      - lib/puppet_x/puppetlabs/*powershell*
      - spec/unit/puppet/type/*
      - spec/integration/**/*
      - spec/unit/puppet_x/puppetlabs/powershell_version_spec.rb
      Include:
      - lib/puppet/type/base_dsc.rb
      - spec/unit/puppet/type/base_dsc_spec.rb
".travis.yml":
  global_env: 
    - HONEYCOMB_WRITEKEY="7f3c63a70eecc61d635917de46bea4e6",HONEYCOMB_DATASET="litmus tests"
  deploy_to_forge:
    enabled: false
  simplecov: true
appveyor.yml:
  unmanaged: true
Gemfile:
  required:
    ":system_tests":
    - gem: puppet-module-posix-system-r#{minor_version}
      platforms: ruby
    - gem: puppet-module-win-system-r#{minor_version}
      platforms:
      - mswin
      - mingw
      - x64_mingw
    - gem: beaker-testmode_switcher
      version: "~> 0.4"
    - gem: master_manipulator
    - gem: puppet-blacksmith
      version: "~> 3.4"
  optional:
    ":build":
    - gem: cim
    - gem: mof
      git: https://github.com/puppetlabs/mof.git
      ref: f50581901c53ff6a40c54b72ef5f4fcaed9679a1
    - gem: charlock_holmes
    - gem: iconv
      version: "~> 1.0.4"
      condition: Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.0')
    ":development":
    - gem: rspec-puppet
      platforms:
      - mswin
      - mingw
      - x64_mingw
      version: "< 2.6.0"
    - gem: 'github_changelog_generator'
      git: 'https://github.com/skywinder/github-changelog-generator'
      ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
      condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"
Rakefile:
  unmanaged: true
spec/spec_helper.rb:
  unmanaged: true
  coverage_report: true
.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false
