---
.gitignore:
  paths:
    - bin
    - import
    - .tmp
    - .rbenv-gemsets
    - .ruby-version
    - "*.lock"
    -  "!build/vendor/"

Gemfile:
  required:
    ':system_tests':
      - gem: 'puppet-module-posix-system-r#{minor_version}'
        platforms: ruby
      - gem: 'puppet-module-win-system-r#{minor_version}'
        platforms:
          - mswin
          - mingw
          - x64_mingw
      - gem: beaker-testmode_switcher
        version: '~> 0.4'
      - gem: master_manipulator
      - gem: puppet-blacksmith
        version: '~> 3.4'
  optional:
    ':build':
      - gem: cim
      - gem: mof
        git: 'https://github.com/puppetlabs/mof.git'
        ref: 'f50581901c53ff6a40c54b72ef5f4fcaed9679a1'
      - gem: charlock_holmes
      - gem: iconv
        version: '~> 1.0.4'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.0')"
    ':development':
      - gem: 'rspec-puppet'
        platforms: ["mswin", "mingw", "x64_mingw"]
        version: '< 2.6.0'

# For the moment don't do any rubocop checks.
.rubocop.yml:
  include_todos: true
  selected_profile: off

# The rakefile is heavily modified for the build process
Rakefile:
  unmanaged: true

spec/default_facts.yml:
  unmanaged: true

# The DSC module doesn't support parallel_spec
appveyor.yml:
  appveyor_bundle_install: "bundle install --jobs 4 --retry 2 --without system_tests build"
  matrix:
    - RUBY_VERSION: 24-x64
      CHECK: "syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop"
    - PUPPET_GEM_VERSION: ~> 4.0
      RUBY_VERSION: 21
      CHECK: spec
    - PUPPET_GEM_VERSION: ~> 4.0
      RUBY_VERSION: 21-x64
      CHECK: spec
    - PUPPET_GEM_VERSION: ~> 5.0
      RUBY_VERSION: 24
      CHECK: spec
    - PUPPET_GEM_VERSION: ~> 5.0
      RUBY_VERSION: 24-x64
      CHECK: spec
    - PUPPET_GEM_VERSION: ~> 6.0
      RUBY_VERSION: 25
      CHECK: spec
    - PUPPET_GEM_VERSION: ~> 6.0
      RUBY_VERSION: 25-x64
      CHECK: spec

.gitlab-ci.yml:
  delete: true
